name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.7
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.7'
    - name: Install Bundler
      run:  gem install bundler
    - name: Install Ruby Dependencies
      run: |
        bundle --version
        bundle install --jobs 4 --retry 3
    - name: Run Tests
      env:
        RAILS_ENV: test
      run: bundle exec rake
